version: '3.9'
services:
  # Database
  db:
    image: mysql:8.0.32
    restart: always
    # Lưu trữ db ngoài container
    command: >
      --bind-address=0.0.0.0
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      # Tạo 1 database ant_home
      MYSQL_DATABASE: anthome_db
    ports:
      - '3306:3306'
  # Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./website:/usr/share/nginx/website
    links:
      - app
    depends_on:
      - app
      - phpmyadmin
  # Nodejs
  app:
    # image: 18.15.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_NAME: anthome_db
      DB_USER: root
      DB_PASS: 12345
      DB_HOST: db
    depends_on:
      - db
  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    # Biến
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345
      #
      PMA_ABSOLUTE_URI: http://anthome.site:8080/
      PMA_ENABLE_CREDENTIALS: 'true'
    ports:
      - '8080:80'
    volumes:
      - ./phpmyadmin:/usr/share/phpmyadmin
    depends_on:
      - db
volumes:
  data:
