# V1.2
version: '3.9'
services:
  # Nginx
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./www:/usr/share/nginx/www
      - phpmyadmin:/var/www/html
    links:
      - app
    depends_on:
      - app
  # Certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    # restart: on-failure
    command: certonly --webroot --webroot-path=/var/www/certbot --email trungkhiem1412@gmail.com --agree-tos --no-eff-email --renew-by-default -d anthome.site -d www.anthome.site
  # Nodejs
  app:
    # image: 18.15.0-alpine
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_NAME: anthome_db
      DB_USER: root
      DB_PASS: 12345
      DB_HOST: db
